version: '2'
services:
  elasticsearch1:
    container_name: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch2,elasticsearch3"
      - "discovery.zen.minimum_master_nodes=2"
      - "xpack.security.enabled=false" #Disable security to make the setup and upgrade easier
      - "xpack.watcher.enabled=false" #Disable watcher to avoid unnecessary activity
      - "xpack.monitoring.enabled=false" #Disable monitoring to avoid unnecessary activity
      - "network.host=0.0.0.0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - /home/ailab/rush.ai/elk/data/es1:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - RUSH.AI

  elasticsearch2:
    container_name: elasticsearch2
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch3"
      - "discovery.zen.minimum_master_nodes=2"
      - "xpack.security.enabled=false" #Disable security to make the setup and upgrade easier
      - "xpack.watcher.enabled=false" #Disable watcher to avoid unnecessary activity
      - "xpack.monitoring.enabled=false" #Disable monitoring to avoid unnecessary activity
      - "network.host=0.0.0.0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - /home/ailab/rush.ai/elk/data/es2:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    networks:
      - RUSH.AI

  elasticsearch3:
    container_name: elasticsearch3
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2"
      - "discovery.zen.minimum_master_nodes=2"
      - "xpack.security.enabled=false" #Disable security to make the setup and upgrade easier
      - "xpack.watcher.enabled=false" #Disable watcher to avoid unnecessary activity
      - "xpack.monitoring.enabled=false" #Disable monitoring to avoid unnecessary activity
      - "network.host=0.0.0.0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - /home/ailab/rush.ai/elk/data/es3:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
    networks:
      - RUSH.AI

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:6.8.13
    command: -f /etc/logstash/conf.d/
    volumes:
      - /home/ailab/rush.ai/elk/config:/etc/logstash/conf.d
    networks:
      - RUSH.AI
    depends_on:
      - elasticsearch1

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.8.13
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch1:9200"
    ports:
      - 5601:5601
    links:
      - elasticsearch1
    depends_on:
      - elasticsearch1
    networks:
      - RUSH.AI
 
volumes:
  data:
    driver: local

networks:
  RUSH.AI:
